### ISSUE TITLE
Configure Ruby with option --enable-shared for Rice

### ISSUE THREAD

**Issue by kojix2** [ankane/torch-rb#3]
Hello.
Thank you for developing a great library.

I wrote an article at Qiita about trying mnist on Torch-rb. (Japanese)
https://qiita.com/kojix2/items/c19c36dc1bf73ea93409

I had to reinstall the ruby for rice.
* Ubuntu 19.04 rbenv ruby 2.6.5
```
CONFIGURE_OPTS="--enable-shared" rbenv install 2.6.5
```
Other than that, there was no problem.

Thank you. And good luck!

**Comment by ankane** [comment]
Awesome, thanks @kojix2!

How did you install rbenv? `--enabled-shared` is the default in newer versions.

**Comment by ankane** [comment]
Also, added the link to the readme :) Let me know if there's something better than 日本語版.

**Comment by kojix2** [comment]
> How did you install rbenv?
I installed rbenv according to the README, so I don't think I did anything unusual. Maybe.

> added the link to the readme
Wow. It's just a small blog post. It's nothing. Thanks !

**Comment by ankane** [comment]
When you say the readme, are you referring to the [git checkout method](https://github.com/rbenv/rbenv#basic-github-checkout)? Also, how did you install ruby-build?

**Comment by kojix2** [comment]
> are you referring to the GitHub checkout method?

Yes.

> Did you install it recently or over a month ago?

Yes. Now I found the commit below in ruby-build. 
https://github.com/rbenv/ruby-build/commit/dd1562ed65f0d681669903eaf4c5764de789a0db
It was because I built Ruby more than a month ago. Thanks.
